# Outliers in production and consumption datasets

In [1]:
%reset
# from __future__ import division
#Importing packages for analyzing useses
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Import the data and making a dataframe out of it
file_name = '../Data/dataGM_excel2.xlsx'
productionDF = pd.read_excel(file_name, sheet_name='Productie')
consumptionDF = pd.read_excel(file_name, sheet_name='Consumptie')


Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [2]:
productionDF.head()

ID-nummer            H01            H02            H03  \
0              concept              E              E             WP   
1            PV-aantal             17             14              9   
2             personen              4              2              4   
3       Datum-tijd tot  Productie kWh  Productie kWh  Productie kWh   
4  2017-07-11 00:15:00              0              0              0   

             H04            H05            H06            H07            H08  \
0             WP             WP              E              E              E   
1             11             12             14             13              9   
2              1              4              4              2              4   
3  Productie kWh  Productie kWh  Productie kWh  Productie kWh  Productie kWh   
4              0            NaN              0              0              0   

             H09  ...            H24            H25            H26  \
0              E  ...             WP            Zon             WP   
1             14  ...             11             13             12   
2              1  ...              2              2              2   
3  Productie kWh  ...  Productie kWh  Productie kWh  Productie kWh   
4              0  ...              0              0              0   

             H27            H28            H29            H30            H31  \
0             WP            Zon              E              E             WP   
1              9             13             14             14             15   
2              3              2              1              4              2   
3  Productie kWh  Productie kWh  Productie kWh  Productie kWh  Productie kWh   
4              0              0              0              0              0   

             H32            H33  
0            Zon             WP  
1             12             10  
2              4              1  
3  Productie kWh  Productie kWh  
4              0              0  

[5 rows x 34 columns]

In [3]:
datos_prod = productionDF.values
datos_consumo = consumptionDF.values
#datos_consumo = datos_prod.transpose()
datos = np.delete(datos_prod, (0), axis = 1)
datos = np.delete(datos, (0,1,2,3), axis = 0)

In [4]:
#consumptionDF.iloc[4:3076,0:33]
data_prod = productionDF.values
data_cons = consumptionDF.values
#datos_consumo = datos_consumo.transpose()
datos = np.delete(data_prod, (0), axis = 1)
datos = np.delete(datos, (0,1,2,3), axis = 0)
#datos = np.delete(datos_consumo, (0), axis = 0)
#datos = np.delete(datos, (0,1,2,3), axis = 1)

print(datos)

datos = pd.DataFrame(datos) #converts to DataFrame

#len(datos)



#datos = datos.fillna(0.0).astype(int)

#datos = datos.fillna(0)

datos.head()


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0  1  2  3    4  5  6  7  8  9   ... 23 24 25 26 27 28 29 30 31 32
0  0  0  0  0  NaN  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  NaN  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
2  0  0  0  0  NaN  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
3  0  0  0  0  NaN  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
4  0  0  0  0  NaN  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0

[5 rows x 33 columns]

In [5]:
num_casa = 12
num_casa = num_casa - 1
casa_prod = datos[num_casa]
#casa_prod.info()

In [10]:
num_panels = 8 #for the 6th house
max_prod = num_panels * 0.25 * 0.25
#max_prod = (75*230)/4000 # 75 max per hour, 230 volts, divided by 4 (15 mins) * 1000 (converts to kwh)
#max_cons = 1
print(max_prod)

0.5


In [11]:
count = 0
for i in range(len(casa_prod)):
    if casa_prod[i] > max_prod:
        count +=1
        print('outlier at the row: ' + str(i+6)) 
        
        
print('\nnumber of outliers: [' + str(count)+ ']')      

outlier at the row: 63
outlier at the row: 155
outlier at the row: 157
outlier at the row: 159
outlier at the row: 167
outlier at the row: 249
outlier at the row: 255
outlier at the row: 256
outlier at the row: 258
outlier at the row: 261
outlier at the row: 262
outlier at the row: 342
outlier at the row: 351
outlier at the row: 352
outlier at the row: 353
outlier at the row: 354
outlier at the row: 355
outlier at the row: 356
outlier at the row: 357
outlier at the row: 358
outlier at the row: 359
outlier at the row: 434
outlier at the row: 435
outlier at the row: 439
outlier at the row: 442
outlier at the row: 445
outlier at the row: 447
outlier at the row: 450
outlier at the row: 535
outlier at the row: 536
outlier at the row: 622
outlier at the row: 623
outlier at the row: 624
outlier at the row: 625
outlier at the row: 626
outlier at the row: 629
outlier at the row: 630
outlier at the row: 631
outlier at the row: 632
outlier at the row: 634
outlier at the row: 635
outlier at the ro

outlier at the row: 28421
outlier at the row: 28462
outlier at the row: 28463
outlier at the row: 28464
outlier at the row: 28465
outlier at the row: 28466
outlier at the row: 28472
outlier at the row: 28474
outlier at the row: 28476
outlier at the row: 28477
outlier at the row: 28478
outlier at the row: 28479
outlier at the row: 28480
outlier at the row: 28481
outlier at the row: 28482
outlier at the row: 28483
outlier at the row: 28484
outlier at the row: 28485
outlier at the row: 28487
outlier at the row: 28488
outlier at the row: 28489
outlier at the row: 28490
outlier at the row: 28558
outlier at the row: 28559
outlier at the row: 28560
outlier at the row: 28561
outlier at the row: 28562
outlier at the row: 28564
outlier at the row: 28565
outlier at the row: 28566
outlier at the row: 28567
outlier at the row: 28568
outlier at the row: 28569
outlier at the row: 28570
outlier at the row: 28571
outlier at the row: 28572
outlier at the row: 28573
outlier at the row: 28574
outlier at t

outlier at the row: 58953
outlier at the row: 59817
outlier at the row: 63845

number of outliers: [1966]


In [8]:
len(casa_prod)

66240

In [9]:
casa_prod[2]

0